import Head from "next/head";
import Image from "next/image";
import Container from "@mui/material/Container";
import MainContainer from "../components/MainContainer.tsx";
import Header from "../components/Header.tsx";
import Box from "@mui/material/Box";
import Carousel from "../components/Carousel.tsx";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Movie Anime Apps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Carousel />
      <MainContainer></MainContainer>
    </div>
  );
}
